import './globals.css'
import Link from 'next/link';
import styles from './hero.module.css'

export const metadata = {
  title: 'Next Tripper Press',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="zh-cn">
      <body>
        <div className={`${styles.header} w-screen h-[58px] shadow-sm`}>
          <Link className='' href="/">Home</Link>
          <Link className='' href="/posts">Posts</Link>
          <Link className='' href="/about">About</Link>
        </div>
        {children}
      </body>
    </html>
  )
}
